type USDADataEntry = {
  PRICE_WHOLESALE: number;
  PRICE_GROWN: number;
};

export const mockUSDAData = {
  CARROTS: {
    PRICE_WHOLESALE: 15.5,
    PRICE_GROWN: 3.2,
  },
  CORN: {
    PRICE_WHOLESALE: 12.3,
    PRICE_GROWN: 4.5,
  },
  CABBAGE: {
    PRICE_WHOLESALE: 10.1,
    PRICE_GROWN: 2.8,
  },
  BLUEBERRIES: {
    PRICE_WHOLESALE: 25.0,
    PRICE_GROWN: 6.3,
  },
  GARLIC: {
    PRICE_WHOLESALE: 20.0,
    PRICE_GROWN: 5.0,
  },
  ONION: {
    PRICE_WHOLESALE: 9.8,
    PRICE_GROWN: 2.4,
  },
  PEPPERS: {
    PRICE_WHOLESALE: 18.7,
    PRICE_GROWN: 4.9,
  },
  BASIL: {
    PRICE_WHOLESALE: 30.0,
    PRICE_GROWN: 8.5,
  },
  BROCCOLI: {
    PRICE_WHOLESALE: 13.4,
    PRICE_GROWN: 3.9,
  },
  ROSES: {
    PRICE_WHOLESALE: 40.0,
    PRICE_GROWN: 10.0,
  },
  GREEN_BEANS: {
    PRICE_WHOLESALE: 14.5,
    PRICE_GROWN: 4.0,
  },
  POTATOES: {
    PRICE_WHOLESALE: 11.0,
    PRICE_GROWN: 2.7,
  },
  PUMPKINS: {
    PRICE_WHOLESALE: 16.3,
    PRICE_GROWN: 5.6,
  },
  ROSEMARY: {
    PRICE_WHOLESALE: 28.0,
    PRICE_GROWN: 7.8,
  },
};
