type USDADataEntry = {
  PRICE_WHOLESALE: number;
  PRICE_GROWN: number;
  AMOUNT_TYPE: string;
};

//Sets a PRICE_WHOLESALE (retail price) and a PRICE_GROWN (DIY) for each plant
//Amount to be added later
export const USDAData = {
  BASIL: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  PEPPERS: {
    PRICE_WHOLESALE: 2.99,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  BLUEBERRIES: {
    PRICE_WHOLESALE: 8.00,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  BROCCOLI: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  CABBAGE: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  CARROTS: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  CORN: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  GARLIC: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  GREEN_BEANS: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  LILLIES: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  ONIONS: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  POTATOES: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  PUMPKINS: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  ROSES: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  ROSEMARY: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  SAGE: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  STRAWBERRIES: {
    PRICE_WHOLESALE: 3.99,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  TOMATOES: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
  TULIPS: {
    PRICE_WHOLESALE: 0,
    PRICE_GROWN: 0,
    AMOUNT_TYPE: "CWT",
  },
};
